application: wattwerkz
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /.*/css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*/js
  static_dir: js
- url: /(.*\.(gif|png|jpg))$
  #static_dir: ../images
  static_files: ../images/\1
  upload: images/.*\.(gif|png|jpg)$
- url: /.*/(.*\.(gif|png|jpg))$
  #static_dir: ../images
  static_files: ../images/\1
  upload: images/.*\.(gif|png|jpg)$
- url: /.*
  script: _go_app
#  login: required
